### PR TITLE
Fixed :: Improper logs in sqlite db

### PR DESCRIPTION
**Pull request by SkMishra77**
**Description:**

Added a condition to check if the Dialect is sqlite then do not log the addr and port.
Closes : #968 

image

### CODE REVIEW

**Review by aryanmehrotra — CHANGES_REQUESTED** [review]
Cognitive complexity is high - rather than lot of if else it can be modified to create and log the fields provided by the user

**Comment by SkMishra77** [comment]
@aryanmehrotra Have a Look !!

**Comment by srijan-27** [comment]
@SkMishra77 - There are few linter errors, try running `golangci-lint run` on local. Also, I think we can add tests for these logs.

**Comment by SkMishra77** [comment]
@srijan-27 Can you Help me to identify that how to write testcase for the retryConnection function as it is infinite running function !

**Comment by srijan-27** [comment]
> @srijan-27 Can you Help me to identify that how to write testcase for the retryConnection function as it is infinite running function !

you don't need to specifically write tests for that function, it can be tests along with its master function (NewSQL).
Reference: https://github.com/gofr-dev/gofr/blob/development/pkg/gofr/datasource/sql/sql_test.go#L259

**Comment by aryanmehrotra** [comment]
@SkMishra77 apologies for a late response, could you please check how we are logging using structs - such that you can remove those if else.
https://github.com/gofr-dev/gofr/blob/development/pkg/gofr/datasource/cassandra/logger.go

Here we are pretty printing but you If you can check the QueryLog struct.
As it hampers the readability to have these many if else.

**Comment by vipul-rawat** [comment]
Closing due to stale activity.

**Pull request closed without merging**
