### PR TITLE
[WIP] REFACTOR: parseRange func & error messages

### PR DESCRIPTION
**Pull request by nidhey27**
Closes: #1000 

**Description:**

#### Refactor `parseRange` Function

This PR refactors the `parseRange` function in the `cron` file to enhance error handling and improve parsing logic. The changes include:

- **Updated Error Handling:**
  - Enhanced error messages for `errOutOfRange` and `errParsing` to provide clearer and more accurate information.

- **Refactored Functions:**
  - **`parseRange`:** Improved error handling and parsing logic for ranges and individual values.
  - **`processPart`:** Refined handling of both value and range parts.
  - **`handleValue`:** Enhanced error reporting for out-of-range values.
  - **`handleRange`:** Added checks for invalid range formats and adjusted error messages.

- **Added Unit Tests:**
  - Comprehensive tests for `processPart`, `handleValue`, and `handleRange` to cover various edge cases and validate the refactored logic.

**Checklist:**

-   [x] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [x] All new code is covered by unit tests.
-   [x] This PR does not decrease the overall code coverage.
-   [ ] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

### CODE REVIEW

**Comment by nidhey27** [comment]
@aryanmehrotra  could you please take a look at the PR?
As `cron.go` file exceeds the line limit, and as we are refactoring the code to enhance maintainability and readability. 

I have Refactored by organizing `cron.go` to hold main structs and functions, `parser.go` for parsing logic, `errors.go` for custom errors, and `regex.go` for regex patterns. This modular approach enhances code readability, maintainability, and separation of concerns.

Any suggestions?

**Comment by aryanmehrotra** [comment]
@nidhey27 if we can create an internal directory and keep these there it will make sure that it is clean.
Moreover, we can unexport the variables in the regex file.

**Comment by nidhey27** [comment]
@aryanmehrotra Could you please elaborate on what exactly needs to be moved to internal?

**Comment by aryanmehrotra** [comment]
> @aryanmehrotra Could you please elaborate on what exactly needs to be moved to internal?

errors.go, parser.go and regex.go can be moved to internal - as it is not being used elsewhere.

check if it is possible to put into a sub-directory cron inside internal

**Comment by aryanmehrotra** [comment]
Hey, I am closing this PR as it is WIP, feel free to open when it is ready for review.

**Pull request closed without merging**
