### PR TITLE
feat: Implement custom favicon support

### PR DESCRIPTION
**Pull request by iamshubha**
- Add support for a custom favicon by checking for a file named favicon.ico in a designated public directory.
- Read favicon path from environment variable for flexibility.

### CODE REVIEW

**Comment by aryanmehrotra** [comment]
@iamshubha as described in the issue ticket, rather than taking the filepath from the user, we would want it to be in static directory, with a file named favicon.ico.

I.E.  If favicon.ico is present in static directory of project's root we will load it, else we will be loading the default favicon.

**Comment by iamshubha** [comment]
Hi @aryanmehrotra, I wanted to let you know that I have made the necessary changes and tested it locally. Please review and let me know if any changes are required.

**Comment by vikash** [comment]
We should write a test as well.

**Comment by aryanmehrotra** [comment]
@iamshubha Changes seem fine, can you write tests as well, and fix code quality.
Also, a debug log can be added for the case when we are rendering custom favicon.ico given by user.

**Comment by srijan-27** [comment]
Closing this as already implemented in #571

**Pull request closed without merging**
