### PR TITLE
typos suggestion

### PR DESCRIPTION
**Pull request by ccoVeille**
## Pull Request Template

**Description:**

- **docs: fix acronyms and brands**
- **docs: fix typos**
- **docs: fix style**

Motivation: typos are bad :grinning: 

**Breaking Changes (if applicable):**

None

**Additional Information:**

I used the following tools to identify most of the issues:
- https://github.com/crate-ci/typos
- https://github.com/languagetool-org/languagetool

**Checklist:**

-   [ ] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [ ] All new code is covered by unit tests.
-   [ ] This PR does not decrease the overall code coverage.
-   [X] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

### CODE REVIEW

**Review by Umang01-hash — APPROVED** [review]

**Review by aryanmehrotra — APPROVED** [review]

**Comment by aryanmehrotra** [comment]
@ccoVeille can you update your branch - not sure why we are not getting update branch option for this PR.

**Comment by ccoVeille** [comment]
I started using an organization for my forks to reduce the noise in my project.

As it's an organization owning the repository, I think I need to configure things

Anyway, I updated

**Comment by ccoVeille** [comment]
> @ccoVeille can you update your branch - not sure why we are not getting update branch option for this PR.

For anyone interested, I created an issue on my own project to tackle this

https://github.com/ccoVeille/github-forks-sanitizer/issues/3#issue-2729309577

**Comment by ccoVeille** [comment]
> @ccoVeille can you update your branch - not sure why we are not getting update branch option for this PR.

I sent you an invitation to collaborate on my fork, it should be ok now

**Pull request merged**
