### PR TITLE
Support AutoMigrate #3

### PR DESCRIPTION
**Pull request by reski-rukmantiyo**
Extended from: #725
Closes: #723, #888

- support for primary_key, auto_increment, not_null, unique, index, and unique_index,check,comment in gofr tags : change into sql meta tag
- support for int, float, bool, string and time.Time in JSON type
- support foreign key as well

### CODE REVIEW

**Comment by Umang01-hash** [comment]
@reski-rukmantiyo Seems like you have some failing test and linters. Please fix them

**Comment by ccoVeille** [comment]
I reviewed the wrong PR, 😱🤦‍♂️

- https://github.com/gofr-dev/gofr/pull/725

Please take a look at them anyway

**Comment by srijan-27** [comment]
@reski-rukmantiyo - Just wanted to know if you are working on this?

**Comment by reski-rukmantiyo** [comment]
> @reski-rukmantiyo - Just wanted to know if you are working on this?

Hi, still working on it. Need more time to fix this. Thanks

**Comment by Umang01-hash** [comment]
@reski-rukmantiyo Hey!
Hope you are still involved in the PR.
Please let us know if you want any help regarding the issue or the PR.

thankyou

**Comment by srijan-27** [comment]
@Umang01-hash - Seems like @reski-rukmantiyo has been busy, can you please take this up.

**Comment by Umang01-hash** [comment]
The work of this PR has been addressed and continued in PR #931. Closing here

**Pull request closed without merging**
