### PR TITLE
Modified Command Interface along with helper function

### PR DESCRIPTION
**Pull request by KedarisettiSreeVamsi**
## Pull Request Template
Modified Command Interface alongside adding helper function for the issue #568. Modified the example with updated code interface.

**Description:**

-   Provide a concise explanation of the changes made.
-   Mention the issue number(s) this PR addresses (if applicable).
-   Highlight the motivation behind the changes and the expected benefits.

**Breaking Changes (if applicable):**

-   List any breaking changes introduced by this PR.
-   Explain the rationale behind these changes and how they will impact users.

**Additional Information:**

-   Mention any relevant dependencies or external libraries used.
-   Include screenshots or code snippets (if necessary) to clarify the changes.

**Checklist:**

-   [ ] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [ ] All new code is covered by unit tests.
-   [ ] This PR does not decrease the overall code coverage.
-   [ ] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

### CODE REVIEW

**Comment by vipul-rawat** [comment]
@KedarisettiSreeVamsi We are closing this PR as it was assigned to @IvanGael and this is a duplicate PR.

**Comment by KedarisettiSreeVamsi** [comment]
Hi @vipul-rawat ,
I understand that this PR has a part of #568 but I have made changes in command line interface which acts as a major point for which I raised the PR. When I was testing the interface I found some issues with regex matching when a particular subcommand pattern acts as a subpattern for another subcommand.
Example: if we take the example code where we have hello subcommand and when I tested with h as in helper subcommand and when I was testing for hello it was invoking h handler. So I thought this PR will make required changes to apply proper handling of subcommands.

**Comment by vipul-rawat** [comment]
Hey @KedarisettiSreeVamsi if you could remove the part that solves #568 we can reopen this PR, as it will cause conflicts. Also please create issue which explains the bug in detail so we can discuss and track the same.
Please avoid creating PR without Issues, as it increases difficulties in maintaining and tracking the progress.

**Comment by KedarisettiSreeVamsi** [comment]
If possible, can you ask IvanGael to review this PR and make changes accordingly so that it will be easier to make it merge compliant. He is not taking my suggestions even after presenting him the option.

**Comment by IvanGael** [comment]
@KedarisettiSreeVamsi Please explain exactly what changes have you made and the files that have been impacted.

**Comment by IvanGael** [comment]
@KedarisettiSreeVamsi  Please provide the link to your PR or commit

**Comment by KedarisettiSreeVamsi** [comment]
Please refer the files in this PR as I am going to reupload the same PR again after you have made the changes in your PR.

**Comment by IvanGael** [comment]
@KedarisettiSreeVamsi I think it's simpler to wait until my PR is validated and merged. You will implement your changes in a new PR. Because even though this PR refers to the same helper command issue, it's still an another issue.

**Comment by KedarisettiSreeVamsi** [comment]
@IvanGael I do understand it but there is no point in me sending a new helper command through my PR as the issue is assigned on your name and I will have to manage all the merge conflicts so to avoid that it is better if both of our implementations are on the same page so merging the PRs will be simple. Maybe @vipul-rawat can provide his insights.

**Comment by vipul-rawat** [comment]
@KedarisettiSreeVamsi I would recommend you get your PR on par with Ivan's since that will be merged first, and you can continue from there I think.

**Pull request closed without merging**
