### PR TITLE
Decrease log level for 4xx HTTP errors : alternative option

### LINKED ISSUE #1279: Avoid Logging 4XX Status Codes as Errors
### Problem
Currently, 4XX HTTP status codes are logged as errors, which can clutter the logs and mislead monitoring systems. Client-side issues should not be considered server errors.

### Expected Behavior
- 4XX status codes should be treated as info or excluded from error logs.
- Only 5XX status codes should be logged as errors.

### Proposed Solution
- Introduce conditional logging:
  - Log **5XX** status codes as errors.
  - Optionally log **4XX** as info or ignore them entirely.
image

### PR DESCRIPTION
**Pull request by ccoVeille**
## Pull Request Template

**Description:**

This PR is an alternative implementation of what was initiated with

- #1295
- #1298 

It goes further than #1298 as it allows defining the log level for any error, not only the HTTP errors

It also provides a way for user to provide a log level for their custom errors (See [docs/advanced-guide/gofr-errors/page.md](https://github.com/gofr-dev/gofr/blob/development/docs/advanced-guide/gofr-errors/page.md))

Fixes #1279
Replaces #1295
Replaces #1298

**Checklist:**

-   [X] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [X] All new code is covered by unit tests.
-   [X] This PR does not decrease the overall code coverage.
-   [X] I have reviewed the code comments and documentation for clarity.

### CODE REVIEW

**Comment by ccoVeille** [comment]
Can someone tell me why the tests are failing ?

I think it's about port already in use, so it could be related to:
- #1248

**Review by Umang01-hash — COMMENTED** [review]
I think you missed adding the `LogLevel()` method to the **errors** of the `http` package. Without that all the http errors will be printed at ERROR level.

**Review by aryanmehrotra — CHANGES_REQUESTED** [review]
I am doubtful and not convinced.
Right now, all the errors are logged at error level, will it be really beneficial from the user perspective to write a method to set the log level for their errors.

Because errors should be logged at error levels or based on the status code.

I.E 4xx being logged at INFO

**Comment by vipul-rawat** [comment]
In my opinion, since all 4xx logs are client-side errors, they are not actually errors related to the server and should be logged at the INFO level like 2xx logs. Just 5xx logs should be considered errors for the server as they are unexpected and server-side errors.

**Comment by ccoVeille** [comment]
> I think you missed adding the `LogLevel()` method to the **errors** of the `http` package. Without that all the http errors will be printed at ERROR level.

Indeed, I might have forgotten to commit a local file 🤦‍♂️😅

I will take a look.

**Comment by ccoVeille** [comment]
> In my opinion, since all 4xx logs are client-side errors, they are not actually errors related to the server and should be logged at the INFO level like 2xx logs. Just 5xx logs should be considered errors for the server as they are unexpected and server-side errors.

Exactly, having a distinct error level for http error is important.

For example 404 could be a Debug, a 403 could be a warning.

A custom error could have a need to set the log level, the same way they are allowed to have a custom status code.

But also please note the change allows providing a log level to any error in the stack

**Review by Umang01-hash — APPROVED** [review]

**Review by aryanmehrotra — APPROVED** [review]

**Pull request merged**
