### PR TITLE
fix every cmd response is followed by %

### PR DESCRIPTION
**Pull request by aditya028**
The `%` symbol at the end of every response is not actually part of the output . It's a feature of some terminal emulators, including the default terminal in macOS, which display a % or other symbol when the output from the last command does not end with a newline `(\n)`.

Here is the output attached
Screenshot 2024-06-10 at 4 05 16 PM

Closes: https://github.com/gofr-dev/gofr/issues/696

### CODE REVIEW

**Comment by vikash** [comment]
This just fixes the example and not the underlying problem.

**Comment by aditya028** [comment]
okk i will look into it

**Comment by aditya028** [comment]
please reivew it @vikash @srijan-27

**Comment by srijan-27** [comment]
@aditya028 - Did you verified the changes by running the example? If yes, please attach the fixed terminal output.
Also, since now format is changed so some tests are failing, would need to fix them as well.

**Comment by aditya028** [comment]
I have checked the examples and it works fine . Also, in the codebase it is mentioned there is some issue that needs to be resolved 
`TODO - provide proper exit codes here. Using os.Exit directly is a problem for tests.`
Screenshot 2024-06-10 at 4 05 16 PM

**Comment by srijan-27** [comment]
@aditya028 - Yes, that needs to be done someway. If you want you can dive deep and take a look on that, if not, then you can just fix the current tests.

**Comment by srijan-27** [comment]
@aditya028 - Forgot to mention previously, if you look into the TODO task, then create a separate issue and PR for that. As it has separate context than this PR.

**Comment by aditya028** [comment]
ok sure @srijan-27 , for now i will fix the test case for this .

**Comment by aditya028** [comment]
@srijan-27 can you check this

**Comment by srijan-27** [comment]
> @srijan-27 can you check this

@aditya028 - Couple of tests are still failing.. you can check them from the workflows.

**Review by aryanmehrotra — APPROVED** [review]

**Review by srijan-27 — APPROVED** [review]

**Pull request merged**
