### PR TITLE
Support AutoMigrate #2

### PR DESCRIPTION
**Pull request by reski-rukmantiyo**
#725 

- support for primary_key, auto_increment, not_null, unique, index, and unique_index,check,comment in gofr tags : change into sql meta tag
- support for int, float, bool, string and time.Time in JSON type
- support foreign key as well

### CODE REVIEW

**Comment by Umang01-hash** [comment]
@reski-rukmantiyo I hope you are working on completing the issue with mentioned requirements for CRUD from Struct feature. If you have ongoing changes, you can make this PR as draft and open it once completed with the issue.

This will also help you and gofr team to better focus on right things.

**Comment by reski-rukmantiyo** [comment]
Hi @Umang01-hash among those 3 requirements, I already fullfil thru this pull request.

**Comment by Umang01-hash** [comment]
> Hi @Umang01-hash among those 3 requirements, I already fullfil thru this pull request.

How have we taken care of the different tags `primary_key, auto_increment, not_null, unique, index, and unique_index,check,comment in gofr tags`

also i don't see `support for int, float, bool, string and time.Time in JSON type` and `support foreign key as well`

**Comment by reski-rukmantiyo** [comment]
Sorry, i push wrong branch.  Let me move to #830

**Pull request closed without merging**
