### PR TITLE
Fix otlp exporter

### PR DESCRIPTION
**Pull request by srijan-27**
## Pull Request Template

**Description:**

-   Provide a concise explanation of the changes made.
-   Mention the issue number(s) this PR addresses (if applicable).
-   Highlight the motivation behind the changes and the expected benefits.

**Breaking Changes (if applicable):**

-   List any breaking changes introduced by this PR.
-   Explain the rationale behind these changes and how they will impact users.

**Additional Information:**

-   Mention any relevant dependencies or external libraries used.
-   Include screenshots or code snippets (if necessary) to clarify the changes.

**Checklist:**

-   [x] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [x] All new code is covered by unit tests.
-   [x] This PR does not decrease the overall code coverage.
-   [x] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

### CODE REVIEW

**Review by Umang01-hash — DISMISSED** [review]

**Review by aryanmehrotra — APPROVED** [review]

**Comment by ccoVeille** [comment]
Hi guys,

I'm coming back after the battle.

And I see the changes you made apparently to cope with issues that the following PR brought (hi @Sianao 👋)

- #856

The PR and commits look like a quick fix in a hurry.

I assume it was needed, because something was KO maybe.

But now the emergency is over,
could you explain what was the problem?

Also, I would expect now to have tests added to cover what was apparently broken.

My idea here is to have the unit tests to avoid such issues in a later refactoring

**Comment by srijan-27** [comment]
Hi @ccoVeille - this PR was more focused on the refactoring part which was skipped in the previous PR. And also there was an issue with log for GoFr tracer.
I think this PR mislead as a fixing broken issue type, but it was more of a refactoring and readability type.

**Comment by ccoVeille** [comment]
Thanks,it's clearer now.

Do we have a test covering the log issue you mentioned?

I'm still on my phone, I cannot run the code and check

**Comment by srijan-27** [comment]
Yes, the log is covered in test, and the test was also updated for the same in the previous PR. And since, I already discussed this with Sianao, I created a separate PR for refactoring purpose.

**Comment by ccoVeille** [comment]
Thanks

**Pull request merged**
